### ISSUE TITLE
`Ray.Create` error : `Propertys is not a valid member of Vector`

### ISSUE THREAD

**Issue by NobleDraconian** [JakeyWasTaken/CeiveImGizmo#6]
Currently, as of `v3.4.0`, if you call `Gizmo.Ray:Create()`, the following error is spit:
```lua
Propertys is not a valid member of Vector3
Script 'ReplicatedStorage.Packages._Index.jakeywastaken_imgizmo@3.4.0.imgizmo.Gizmos.Ray', Line 49 - function Create
```

To reproduce, simply run the following code:
```lua
local Gizmo = require(ReplicatedStorage.Packages.Gizmo)

Gizmo.Init()

local DebugRay = Gizmo.Ray:Create(Vector3.new(0, 0, 0), Vector3.new(1, 1, 1))
```

**Comment by JakeyWasTaken** [comment]
I'm unable to reproduce this error, have you done any source modification?

**Comment by NobleDraconian** [comment]
I have not modified the source at all. Will try to get a different repro

**Comment by JakeyWasTaken** [comment]
Just going to close this, will reopen if issue resurfaces.
